name: 'email-license-report-action'
description: 'Generates and sends an email to a list of email addresses with the report of users in an enterprise'
author: 'GitHub'
inputs:
  token:
    required: true
    description: 'A personal access token with permissions on all the orgs of the enterprise'
  enterprise:
    required: true
    description: 'The enterprise where we want to generate the report'
  format:
    required: true
    description: 'Determines how the output parameter will be formatted. Supports: json, markdown and html'
outputs:
  data: 
    description: 'The data extracted from the license API calls in the format specified. The type of the output is always string'
runs:
  using: 'node12'
  main: 'dist/index.js'
