name: 'email-license-report-action'
description: 'Generates and sends an email to a list of email addresses with the report of users in an enterprise'
author: 'GitHub'
inputs:
  token:
    required: true
    description: 'A personal access token with permissions on all the orgs of the enterprise'
  enterprise:
    required: true
    description: 'The enterprise where we want to generate the report'
  emails:
    required: true
    description: 'The emails, comma separated, where the report will be sent'
  smtp_host:
    required: true
    description: 'The host of the smtp server'
  smtp_port:
    required: true
    description: 'The port of the smtp server'
  sender:
    required: false
    description: 'The name of the sender'
    default: GitHub
  subject:
    required: false
    description: 'The name of the email subject'
    default: GitHub Report
runs:
  using: 'node12'
  main: 'dist/index.js'
