name: Node.js test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - run: npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present

      - run: npm run test --if-present
